

export const  productList = [
    {
        name:"Fortnite",
        type:"Sandbox",
        id: 1,
        price: 48,
        image: "fornite1.jpg",
        image1: "feature-left.jpg",
        image2: "feature-right.jpg",
        image3: "details-01.jpg",
        image4: "details-02.jpg",
        image5: "details-03.jpg",
        video: "https://www.youtube.com/watch?v=G8D8xVwhRy8&ab_channel=YEAH1SHOW",
        description: "Fornite là một tựa game không còn quá xa lạ với các fan của Fornite. Game thuộc thể loại battle royale kết hợp cách chơi xây dựng mới lạ và hấp dẫn chắc chắn sẽ thu hút đông đảo người chơi.",
        bought: "5M"
    },
    {
        name:"PubG",
        type:"Battle S",
        id: 2,
        image: "pubg6.jpg",
        image1: "pubg1.jpg",
        image2: "pubg2.jpg",
        image3: "pubg3.jpg",
        image4: "pubg4.jpg",
        image5: "pubg5.jpg",
        description: "Hạ cánh trên các địa điểm chiến lược, cướp vũ khí và vật tư, và sống sót để trở thành đội cuối cùng đứng trên các Chiến trường đa dạng, phong phú.\n" +
            "Lập đội và tham gia Battlegrounds để có trải nghiệm Battle Royale nguyên bản mà chỉ PUBG: BATTLEGROUNDS mới có thể cung cấp.",
        price: 50,
        bought: "10M"
    },
    {
        name:"Dota2",
        type:"Steam-X",
        id: 3,
        image: "dota1.jpg",
        image1: "dota2.jpg",
        image2: "dota3.jpg",
        image3: "dota4.png",
        image4: "dota5.jpg",
        image5: "dota4.png",
        price: 48,
        bought: "2.3M"
    },
    {
        name:"CSGO-2",
        type:"Steam-X",
        id: 7,
        image: "csgo2.png",
        image1: "csgo1.jpg",
        image2: "csgo3.jpg",
        image3: "csgo4.jpg",
        image4: "csgo5.jpg",
        image5: "csgo6.jpg",
        video: "https://www.youtube.com/watch?v=1nkO4N7P-Ys",
        price: 48,
        bought: "2.3M"
    },
    {
        name:"Apex Legend",
        type:"Steam-X",
        id: 8,
        image: "apex2.jpg",
        image1: "apex1.jpg",
        image2: "apex5.jpg",
        image3: "apex3.jpg",
        image4: "apex4.jpeg",
        image5: "apex6.jpg",
        video: "https://www.youtube.com/watch?v=NDQe4Xc6zeo",
        price: 48,
        bought: "2.3M"
    },
    {
        name:"War Thunder",
        type:"Steam-X",
        id: 9,
        image: "wt2.jpg",
        image1: "wt4.jpg",
        image2: "wt3.jpg",
        image3: "wt1.jpg",
        image4: "wt5.jpg",
        image5: "wt6.jpg",
        video: "https://www.youtube.com/watch?v=0-J5Vg0SxLc",
        price: 49,
        bought: "2.3M"
    },
    {
        name:"GTA V",
        type:"Steam-X",
        id: 10,
        image: "gta1.jpg",
        image1: "gta2.jpg",
        image2: "gta6.jpg",
        image3: "gta3.jpg",
        image4: "gta4.jpg",
        image5: "gta5.jpg",
        video: "https://www.youtube.com/watch?v=hvoD7ehZPcM",
        price: 52,
        bought: "2.3M"
    },
    {
        name:"Dota7",
        type:"Steam-X",
        id: 11,
        image: "got1.jpg",
        image1: "got2.jpg",
        image2: "got6.jpg",
        image3: "got3.jpg",
        image4: "got4.jpg",
        image5: "got5.jpg",
        video:"https://www.youtube.com/watch?v=cCL6tWv_7FM",
        price: 39,
        bought: "2.3M"
    },
    {
        name:"Battlefield™ 2042",
        type:"Steam-X",
        id: 12,
        image: "btf2.jpg",
        image1: "btf1.jpg",
        image2: "btf4.jpg",
        image3: "btf3.jpg",
        image4: "btf6.jpg",
        image5: "btf5.jpg",
        video:"https://www.youtube.com/watch?v=ASzOzrB-a9E",
        price: 36,
        bought: "2.3M"
    },

    {
        name:"Mine Craft",
        type:"Steam-X",
        id: 4,
        image: "mc1.jpg",
        image1: "mc2.png",
        image2: "mc3.png",
        image3: "mc4.jpg",
        image4: "mc5.jpg",
        image5: "mc6.jpg",
        video: "https://www.youtube.com/watch?v=Rla3FUlxJdE",
        price: 10,
        bought: "2.3M"
    },
    {
        name:"Goose Goose Duck",
        type:"Matrix Games",
        id: 5,
        image: "duck1.jpg",
        image1: "duck2.jpg",
        image2: "duck3.jpg",
        image3: "duck4.jpg",
        image4: "duck5.jpg",
        image5: "duck6.jpg",
        video: "https://www.youtube.com/watch?v=bHrHDenJlG8",
        price: 70,
        bought: "1M"
    },
    {
        name:"League of Legend",
        type:"Riot",
        id: 6,
        price: 99,
        image: "lol1.jpg",
        image1: "lol6.jpg",
        image2: "lol5.jpg",
        image3: "lol2.jpg",
        image4: "lol3.jpg",
        image5: "lol4.jpg",
        video: "https://www.youtube.com/watch?v=sjrmI2QbPig",
        bought: "5M"
    },
    {
        name:"FC Online",
        type:"Steam-X",
        id: 13,
        image: "fc1.jpg",
        image1: "fc7.jpg",
        image2: "fc6.jpg",
        image3: "fc4.jpg",
        image4: "fc5.jpg",
        image5: "fc2.jpg",
        video: "https://www.youtube.com/watch?v=0Y5vQ2KIFZ8",
        price: 60,
        bought: "5.3M"
    },
    {
        name:"TFT",
        type:"Riot",
        id: 14,
        image: "tft1.jpg",
        image1: "tft6.jpg",
        image2: "tft5.jpg",
        image3: "tft3.jpg",
        image4: "tft4.jpg",
        image5: "tft2.jpg",
        video: "https://www.youtube.com/watch?v=FZ0QPjCs0D4",
        price: 30,
        bought: "5.3M"
    },
]
